2018-11-15 23:03:00,837 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.21
2018-11-15 23:03:00,837 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf/mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs/2018-11-15-23-03-00-mpf-Sean-Pauls-MacBook-Pro.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2018-11-15 23:03:00,837 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf
2018-11-15 23:03:00,837 : INFO : Machine : Machine path: /Users/seanpaulfenton/src/mpf/tutorials
2018-11-15 23:03:00,837 : INFO : Machine : Platform: darwin
2018-11-15 23:03:00,837 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
2018-11-15 23:03:00,838 : INFO : Machine : Python version: 3.6.5 (64-bit)
2018-11-15 23:03:01,118 : INFO : Machine : Machine config file #1: config.yaml
2018-11-15 23:03:01,122 : INFO : ConfigProcessor : Loading config from cache: /var/folders/nx/hjkv90px0cg9f03hrdxkbb700000gn/T/a6640335647e99c19d5eef483964d2ed.mpf_cache
2018-11-15 23:03:01,123 : INFO : Machine : Initialise MPF.
2018-11-15 23:03:01,259 : ERROR : Machine : ERROR: Failed to initialise MPF: curs_set() returned ERR
2018-11-15 23:03:01,264 : INFO : Machine : Starting the main run loop.
2018-11-15 23:03:01,396 : ERROR : root : Event loop is closed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf/commands/game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf/core/machine.py", line 664, in run
    self._run_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf/core/machine.py", line 702, in _run_loop
    self.clock.run(self.stop_future)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mpf/core/clock.py", line 82, in run
    self.loop.run_until_complete(stop_future)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 444, in run_until_complete
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 358, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
